### ISSUE TITLE
Instructions for pm2 hosting setup are not working

### ISSUE THREAD

**Issue by nielsenmarkus11** [trestletech/plumber#63]
I followed the directions on hosting plumber with pm2 [here](http://plumber.trestletech.com/docs/hosting/), however pm2 I get javascript errors as follows:

When `R -e "library(plumber); r<-plumb('plumb-test.R');r\$run(port=8000)"` was used I got 
```
R -e "library(plumber);r <-plumb('plumb-test.R');r\$run(port=8000)"
     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
SyntaxError: Unexpected string
    at Object.exports.runInThisContext (vm.js:76:16)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Function._load (/usr/lib/node_modules/pm2/node_modules/pmx/lib/transaction.js:62:21)
    at Object.<anonymous> (/usr/lib/node_modules/pm2/lib/ProcessContainerFork.js:52:21)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
```

When  I saved the R code as a script and tried `R -f plumb-start.R`, I got:
```
ReferenceError: R is not defined
    at Object.<anonymous> (/usr/local/plumber/hello/plumb-hello:2:1)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Function._load (/usr/lib/node_modules/pm2/node_modules/pmx/lib/transaction.js:62:21)
    at Object.<anonymous> (/usr/lib/node_modules/pm2/lib/ProcessContainerFork.js:52:21)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
```

Am I setting up something incorrectly? Or is this something that `pm2`  does not support?  I'm using version 2.1.5 of `pm2`.

I have successfully been able to run the script as root... I'm not sure what I'm doing wrong.

Thanks.

**Comment by nielsenmarkus11** [comment]
Okay, I see my problem... I need to name my script with the `.sh` extension.
